version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=seu_usuario
      - POSTGRES_PASSWORD=sua_senha
      - POSTGRES_DB=seu_banco
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=seu_usuario
      - DATABASE_PASSWORD=sua_senha
      - DATABASE_NAME=seu_banco

volumes:
  db_data:
